---
- name: Run NGINX Container
  hosts: all
  become: yes

  tasks:

    - name: Run NGINX container
      shell: |
        docker run -d \
          --name nginx-web \
          --restart unless-stopped \
          -p 80:80 \
          nginx:latest

    - name: Create Welcome page inside container
      shell: |
        docker exec nginx-web sh -c \
        'echo "<h1>Welcome to Kubernetes Class</h1>" > /usr/share/nginx/html/index.html'