---
- name: Create user pedram
  hosts: all
  become: yes
  tasks:
    - name: Ensure pedram user exists
      user:
        name: pedram
        comment: "pedram Zolfaghari"
        password: "{{ 'pedram' | password_hash('sha512') }}"
        home: /home/pedram
        shell: /bin/bash
        create_home: yes
