---
- name: Delete user pedram and remove home directory
  hosts: all
  become: yes
  tasks:
    - name: Remove user pedram completely
      user:
        name: pedram
        state: absent
        remove: yes
