---
- name: Delete user leila and remove home directory
  hosts: all
  become: yes
  tasks:
    - name: Remove user leila completely
      user:
        name: leila
        state: absent
        remove: yes
