---
- name: Delete user mamad and remove home directory
  hosts: all
  become: yes
  tasks:
    - name: Remove user mamad completely
      user:
        name: mamad
        state: absent
        remove: yes
