---
- name: Create user akbar and setup environment
  hosts: all
  become: true
  tasks:

    - name: Ensure user akbar exists
      user:
        name: akbar
        comment: "Sanei"
        home: /home/behrad
        shell: /bin/bash
        create_home: yes
        password: "{{ 'behrad' | password_hash('sha512') }}"

    - name: Force password change on first login
      command: chage -d 0 akbar

    - name: Create welcome.txt file for akbar
      copy:
        dest: /home/behrad/welcome.txt
        content: |
          Welcome behrad
          Please check the Jira for your first task.
          Use the same username and password.
          Jira URL: http://anisajira.com
        owner: akbar
        group: akbar
        mode: '0644'
