---
- name: Create user behrad and setup environment
  hosts: all
  become: true
  tasks:

    - name: Ensure user behrad exists
      user:
        name: behrad
        comment: "Sanei"
        home: /home/behrad
        shell: /bin/bash
        create_home: yes
        password: "{{ 'behrad' | password_hash('sha512') }}"

    - name: Force password change on first login
      command: chage -d 0 behrad

    - name: Create welcome.txt file for behrad
      copy:
        dest: /home/behrad/welcome.txt
        content: |
          Welcome behrad
          Please check the Jira for your first task.
          Use the same username and password.
          Jira URL: http://anisajira.com
        owner: behrad
        group: behrad
        mode: '0644'
